-- Eventos: cru (auditoria + replay) e normalizado (§3.2).
-- Ambas as tabelas são particionadas por dia. A limpeza é DROP PARTITION,
-- que é O(1) e não gera VACUUM pesado (§10.2).
--
-- Regra do Postgres: numa tabela particionada, toda chave primária ou índice
-- único PRECISA conter a coluna de partição. Por isso as PKs são compostas.

-- Cru: tudo que chega, sem processar. Retenção 7 dias (§14.1).
CREATE TABLE IF NOT EXISTS events_raw (
  id            bigint GENERATED BY DEFAULT AS IDENTITY,
  source_id     uuid REFERENCES sources(id) ON DELETE SET NULL,
  received_at   timestamptz NOT NULL DEFAULT now(),
  headers       jsonb,
  payload       jsonb NOT NULL,
  -- sha256(source_id + corpo). Plataformas fazem retry com frequência (§4.3).
  dedupe_hash   text,
  signature_ok  boolean,
  processed_at  timestamptz,
  error         text,
  PRIMARY KEY (id, received_at)
) PARTITION BY RANGE (received_at);

-- A deduplicação consulta as últimas 24h por hash (§4.3).
CREATE INDEX IF NOT EXISTS events_raw_dedupe_idx
  ON events_raw (dedupe_hash, received_at DESC) WHERE dedupe_hash IS NOT NULL;
-- Fila de normalização: o que ainda não foi processado.
CREATE INDEX IF NOT EXISTS events_raw_pending_idx
  ON events_raw (received_at) WHERE processed_at IS NULL;
CREATE INDEX IF NOT EXISTS events_raw_source_idx
  ON events_raw (source_id, received_at DESC);

-- Normalizado: é sobre isto que os fluxos disparam. Retenção 30 dias.
CREATE TABLE IF NOT EXISTS events (
  id           bigint GENERATED BY DEFAULT AS IDENTITY,
  org_id       uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  source_id    uuid REFERENCES sources(id) ON DELETE SET NULL,
  -- evento canônico (§4.1)
  type         text NOT NULL,
  -- id do pedido/usuário na origem
  external_id  text,
  contact_id   uuid REFERENCES contacts(id) ON DELETE SET NULL,
  occurred_at  timestamptz NOT NULL DEFAULT now(),
  -- valores normalizados que alimentam as variáveis das mensagens (§6.3)
  data         jsonb NOT NULL DEFAULT '{}'::jsonb,
  raw_id       bigint,
  PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at);

CREATE INDEX IF NOT EXISTS events_org_type_idx
  ON events (org_id, type, occurred_at DESC);
CREATE INDEX IF NOT EXISTS events_contact_idx
  ON events (contact_id, occurred_at DESC);
-- Impede que o mesmo evento da mesma origem entre duas vezes.
CREATE UNIQUE INDEX IF NOT EXISTS events_source_type_external_uq
  ON events (source_id, type, external_id, occurred_at);
-- Suporte a §4.4: dado um order.created, houve order.paid com o mesmo external_id?
CREATE INDEX IF NOT EXISTS events_org_external_idx
  ON events (org_id, external_id, occurred_at DESC) WHERE external_id IS NOT NULL;
