-- Infraestrutura e integrações (§3.8).

-- Credenciais de provedor criptografadas em repouso: AES-256-GCM, chave em
-- ENCRYPTION_KEY, nunca no banco (§14.1). Por isso bytea, não text.
CREATE TABLE IF NOT EXISTS channel_configs (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id                 uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  channel                text NOT NULL
                         CHECK (channel IN ('whatsapp', 'email', 'sms', 'telegram')),
  provider               text NOT NULL,
  credentials_encrypted  bytea,
  rate_limit_per_minute  integer,
  daily_cap              integer,
  active                 boolean NOT NULL DEFAULT true,
  is_default             boolean NOT NULL DEFAULT false,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now()
);

-- Um provedor padrão por canal por organização.
CREATE UNIQUE INDEX IF NOT EXISTS channel_configs_default_uq
  ON channel_configs (org_id, channel) WHERE is_default;
CREATE INDEX IF NOT EXISTS channel_configs_org_idx ON channel_configs (org_id);

-- Instâncias de WhatsApp na Evolution API, com aquecimento e rodízio (§7.3).
CREATE TABLE IF NOT EXISTS wa_instances (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id                uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name                  text NOT NULL,
  evolution_url         text NOT NULL,
  instance_name         text NOT NULL,
  apikey_encrypted      bytea,
  phone_e164            text,
  status                text NOT NULL DEFAULT 'desconectado'
                        CHECK (status IN ('conectando', 'conectado', 'desconectado', 'banido')),
  -- 0 = novo … 5 = consolidado. Define daily_cap e min_interval_seconds (§7.3).
  warmup_stage          smallint NOT NULL DEFAULT 0
                        CHECK (warmup_stage BETWEEN 0 AND 5),
  warmup_started_at     timestamptz,
  daily_cap             integer NOT NULL DEFAULT 20,
  -- Intervalo mínimo entre envios, em segundos. Coluna da escada de §7.3 que a
  -- spec descreve na tabela mas não modela.
  min_interval_seconds  integer NOT NULL DEFAULT 60,
  sent_today            integer NOT NULL DEFAULT 0,
  last_sent_at          timestamptz,
  -- Taxa de falha em 24h. A progressão do aquecimento só avança abaixo de 3%.
  failure_rate_24h      numeric(5, 4) NOT NULL DEFAULT 0,
  last_connected_at     timestamptz,
  proxy_url             text,
  -- peso para o rodízio entre números
  weight                integer NOT NULL DEFAULT 1 CHECK (weight > 0),
  active                boolean NOT NULL DEFAULT true,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS wa_instances_org_name_uq
  ON wa_instances (org_id, instance_name);
CREATE INDEX IF NOT EXISTS wa_instances_org_active_idx
  ON wa_instances (org_id) WHERE active;

-- Chaves da API pública (§12.1). Guardamos só o sha256; o prefixo visível
-- (mandafy_live_a1b2…) serve para o usuário reconhecer a chave na lista.
CREATE TABLE IF NOT EXISTS api_keys (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name          text NOT NULL,
  key_hash      text NOT NULL UNIQUE,
  key_prefix    text NOT NULL,
  scopes        text[] NOT NULL DEFAULT '{}',
  created_by    uuid REFERENCES users(id) ON DELETE SET NULL,
  last_used_at  timestamptz,
  revoked_at    timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS api_keys_org_idx ON api_keys (org_id);

-- Webhooks de saída (§12.3). Assinatura HMAC-SHA256 em X-Mandafy-Signature.
CREATE TABLE IF NOT EXISTS outbound_webhooks (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id         uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  url            text NOT NULL,
  events         text[] NOT NULL DEFAULT '{}',
  secret         text NOT NULL,
  active         boolean NOT NULL DEFAULT true,
  last_status    integer,
  last_error     text,
  last_sent_at   timestamptz,
  -- Após 5 falhas seguidas o webhook é desativado e o admin é alertado (§12.3).
  failure_count  integer NOT NULL DEFAULT 0,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS outbound_webhooks_org_idx ON outbound_webhooks (org_id);

-- Log de auditoria de todo acesso e alteração de dado pessoal (§14.1).
CREATE TABLE IF NOT EXISTS audit_log (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id      uuid REFERENCES organizations(id) ON DELETE CASCADE,
  user_id     uuid REFERENCES users(id) ON DELETE SET NULL,
  action      text NOT NULL,
  entity      text,
  entity_id   text,
  before      jsonb,
  after       jsonb,
  ip          inet,
  user_agent  text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS audit_log_org_created_idx
  ON audit_log (org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS audit_log_entity_idx
  ON audit_log (entity, entity_id, created_at DESC);
